on:
  - pull_request
  - push
name: consumer
jobs:
  consumer_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: consumer
        uses: nats-io/jetstream-gh-action/validate/consumer@master
        with:
          config: action/testdata/consumer.json
