on:
  - pull_request
  - push

name: create_and_delete
jobs:
  test_create_and_delete:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: synadia/jsm:latest
        options: >-
          -e JSM_MODE=server

    steps:
      - uses: actions/checkout@master

      - name: create_orders_stream
        uses: nats-io/jetstream-gh-action/create/stream@master
        with:
          config: action/testdata/ORDERS.json
          server: jetstream

      - name: create_new_consumer
        uses: nats-io/jetstream-gh-action/create/consumer@master
        with:
          stream: ORDERS
          config: action/testdata/ORDERS_NEW.json
          server: jetstream

      - name: publish_order
        uses: nats-io/jetstream-gh-action@master
        with:
          subject: ORDERS.test
          message: Published new deployment via "${{ github.event_name }}" in "${{ github.repository }}"
          should_ack: 1
          server: jetstream

      - name: purge_orders
        uses: nats-io/jetstream-gh-action/purge/stream@master
        with:
          stream: ORDERS
          server: jetstream

      - name: delete_orders_new_consumer
        uses: nats-io/jetstream-gh-action/delete/consumer@master
        with:
          stream: ORDERS
          consumer: NEW
          server: jetstream

      - name: delete_orders_stream
        uses: nats-io/jetstream-gh-action/delete/stream@master
        with:
          stream: ORDERS
          server: jetstream
