on: push
name: empty_json
jobs:
  empty_json_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: empty json
        id: empty_json
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/bad-json.json
  expect_failure:
    runs-on: ubuntu-latest
    needs: empty_json_validate
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: expect_failure
        if: env.WORKFLOW_CONCLUSION == 'success'
        run: exit 1
