on: push
name: stream
jobs:
  stream_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: stream
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/stream.json
