on:
  - pull_request
  - push

name: update
jobs:
  test_update:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: synadia/jsm:latest
        options: >-
          -e JSM_MODE=server

    steps:
      - uses: actions/checkout@main

      - name: create_orders_stream
        uses: nats-io/jetstream-gh-action/create/stream@main
        with:
          config: action/testdata/ORDERS.json
          server: jetstream

      - name: update_orders_stream
        uses: nats-io/jetstream-gh-action/update/stream@main
        with:
          stream: ORDERS
          config: action/testdata/ORDERS-update.json
          server: jetstream
