on:
  - pull_request
  - push
name: validate
jobs:
  bad_json_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: bad json
        id: bad_json
        continue-on-error: true
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/bad-json.json
      - name: expect_failure
        if: steps.bad_json.outcome != 'failure'
        run: exit 1
      - name: report_failure
        if: steps.bad_json.outcome == 'failure'
        run: echo "bad json file succesfully failed to validate"

  consumer_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: consumer
        uses: nats-io/jetstream-gh-action/validate/consumer@master
        with:
          config: action/testdata/consumer.json

  empty_json_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: empty json
        id: empty_json
        continue-on-error: true
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/bad-json.json
      - name: expect_failure
        if: steps.empty_json.outcome != 'failure'
        run: exit 1
      - name: report_failure
        if: steps.empty_json.outcome == 'failure'
        run: echo "empty json file succesfully failed to validate"

  stream_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: stream
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/stream.json
